### PR TITLE
search: removes auto reloading from search.js

### PR DESCRIPTION
**Pull request by ioannistsanaktsidis**
- Closes inspirehep/inspire-next#657.

Signed-off-by: Ioannis Tsanaktsidis ioannis.tsanaktsidis@cern.ch

### CODE REVIEW

**Comment by ioannistsanaktsidis** [comment]
To tell you the truth I think this function 

```
  this.on('facetsEdit', function(ev, data) {
```

can be completely removed. I will check after lunch and update the PR if needed.

**Comment by ioannistsanaktsidis** [comment]
From my testing the function can be completely removed.

**Comment by jmartinm** [comment]
I get an error in Safari

``` javascript
TypeError: null is not an object (evaluating 'window.history.state.facetsFilter')
(anonymous function)search.js:221
```

**Comment by ioannistsanaktsidis** [comment]
I have been working on this problem without finding a good solution. The issue is the first time that the user opens the browser, where the history.state is always null. We have to find a way to set it by default to the search url. Till now the things that I tried break :/

**Comment by jmartinm** [comment]
This seems to work for me http://stackoverflow.com/a/10765676/890185

Implemented here https://github.com/inspirehep/invenio-search/pull/15

**Comment by jmartinm** [comment]
Superseded by https://github.com/inspirehep/invenio-search/pull/15/files

**Pull request closed without merging**
