### PR TITLE
api: query debug information addition

### PR DESCRIPTION
**Pull request by jmartinm**
Signed-off-by: Javier Martin Montull javier.martin.montull@cern.ch

### CODE REVIEW

**Comment by kaplun** [comment]
Since this is for debugging while developing, shall we also amend the Procfile to set the debug level of celery to debug so that we can capture this information?

**Comment by kaplun** [comment]
Can you amend version.py to increment the date?

**Comment by kaplun** [comment]
BTW, I have just merged @Panos512 improvements in #2. Can you just rebase?

**Comment by jmartinm** [comment]
> Can you amend version.py to increment the date?

Actually the 'best practice' we have used is to not increase the version in `version.py` in our forks and just update our `base.requirements.txt` with a new fake version which triggers `pip` to update the package.

**Comment by jmartinm** [comment]
Rebased.

**Comment by kaplun** [comment]
I know, but then I realized it's wrong. Because pip then fetches the master branch, tries to install it and complains that the installed version has older version then the past. So if locally then you try to reinstall dependency once more it will reinstall again this older version complaining each time that it's old.

**Pull request merged**
